%% LaTeX2e file `some.php'
%% generated by the `filecontents' environment
%% from source `test_listing' on 2016/06/24.
%%
$query  = ""
    ."SELECT                        "
    ."    username                  "
    ."FROM                          "
    ."    users                     "
    ."WHERE                         "
    ."    username = '$username'    "
    ."AND                           "
    ."    password = '$password'    ";

$result = mysqli_query($connection, $query);

if(mysqli_num_rows($result) != 0){
    $_SESSION['user_logged_in'] = $username;
}
